logging.level.com.zaxxer.hikari=INFO

http {
    host = localhost
    host = ${?HTTP_HOST}

    port = 8000
    port = ${?HTTP_PORT}
}

auth {
    bcrypt {
        rounds = 10
        rounds = ${?BCRYPT_ROUNDS}
        pepper = ${?BCRYPT_PEPPER}
    }

    dcc-login {
        base-url = ${DCC_LOGIN_URL}
        app-name = ${DCC_LOGIN_APP_NAME}
    }

    jwt {
        secret-key = ${SECRET_KEY}

        access-token-life-seconds = 600
        refresh-token-life-seconds = 604800
        leeway-seconds = 10
    }
}

db {
    host = ${DB_HOST}

    port = 5432
    port = ${?DB_PORT}

    credentials {
        username = ${DB_USER}
        password = ${DB_PASS}

        database = ramitos
        database = ${?DB_NAME}
    }

    hikari {
        maximum-pool-size = ${?HIKARI_POOL_SIZE}
        minimum-idle-millis = ${?HIKARI_MIN_IDLE}
        max-lifetime-millis = ${?HIKARI_MAX_LIFETIME}
        idle-timeout-millis = ${?HIKARI_IDLE_TIMEOUT}
    }
}

app {
    tags = []
}

mufasa {
    base-url = ${MUFASA_BASE_URL}
    token   = ${MUFASA_TOKEN}
}

cfg {
    logging.level.com.zaxxer.hikari=INFO
}
