logging.level.com.zaxxer.hikari=INFO

http {
    host = localhost
    host = ${?HTTP_HOST}

    port = 8000
    port = ${?HTTP_PORT}
}

auth {
    bcrypt {
        rounds = 10
        rounds = ${?BCRYPT_ROUNDS}
        pepper = ${?BCRYPT_PEPPER}
    }

    dcc-login {
        login-time-limit-seconds = 30
        login-time-limit-seconds = ${?DCC_LOGIN_TIME_LIMIT}
    }

    portal-dcc {
        base-url = ${PORTAL_DCC_BASE_URL}
        app-name = ${PORTAL_DCC_APP_NAME}

        jwt {
            secret-key = ${PORTAL_DCC_SECRET_KEY}

            access-token-life-seconds = 0
            refresh-token-life-seconds = 0
            leeway-seconds = 0
        }
    }

    jwt {
        secret-key = ${SECRET_KEY}

        access-token-life-seconds = 999999999
        refresh-token-life-seconds = 999999999
        leeway-seconds = 10
    }
}

db {
    host = ${DB_HOST}

    port = 5432
    port = ${?DB_PORT}

    credentials {
        username = ${DB_USER}
        password = ${DB_PASS}

        database = ramitos
        database = ${?DB_NAME}
    }

    hikari {
        maximum-pool-size = ${?HIKARI_POOL_SIZE}
        minimum-idle-millis = ${?HIKARI_MIN_IDLE}
        max-lifetime-millis = ${?HIKARI_MAX_LIFETIME}
        idle-timeout-millis = ${?HIKARI_IDLE_TIMEOUT}
    }
}

app {
    tags = [
        "mitag1"
        "mitag2"
        {ex = ["tagex1", "tagex2"]}
    ]
}

mufasa {
    base-url = ${MUFASA_BASE_URL}
    token   = ${MUFASA_TOKEN}
}

cfg {
    logging.level.com.zaxxer.hikari=INFO
}
